In [2]:
#numpy converts data into binary
import numpy as np

In [4]:
l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [24]:
#as in the list as string and its higher order, it will convert all the elements into string
# it only matters for the research, as space matters while research
d1=[4,5,6,7,"sudh",34.566,True]
a1 =np.array(l1)
a1.ndim

1

In [12]:
# coverts into two dimentional array
a2 = np.array([[1,2,3],[4,5,6]])

In [13]:
a3=np.array([[[1,2,3],[2,3,4],[3,5,6]]])

In [22]:
a1

[4, 5, 6, 7, 'sudh', 34.566, True]

In [28]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a3

array([[[1, 2, 3],
        [2, 3, 4],
        [3, 5, 6]]])

In [25]:
a1.ndim

1

In [26]:
a2.ndim

2

In [29]:
a3.ndim

3

In [30]:
a1.size

7

In [31]:
a2.size

6

In [32]:
a3.size

9

In [33]:
a1.shape

(7,)

In [34]:
#two rows and 3 columns
a2.shape

(2, 3)

In [36]:
# ((z), y, x) ( z= 1, y =3 , x =3)
a3.shape

(1, 3, 3)

In [41]:
#fist/second parameter is lower bound and uppoer bound, (3 paramenter =  rows and 4 = columns)
np.random.randint(2,50,(3,4))

array([[33, 37, 45, 11],
       [16, 39, 17, 23],
       [ 8,  6, 15,  8]])

In [45]:
#fist/second parameter is lower bound and uppoer bound, (3= depth(z) 4 paramenter =  rows and 6 = columns)
a4 = np.random.randint(2,50,(2,3,4))

In [46]:
a4

array([[[13, 40, 18, 39],
        [ 4, 13, 36, 22],
        [ 9,  3, 27, 13]],

       [[17, 42, 12, 29],
        [46, 12, 31, 28],
        [41, 21, 20, 11]]])

In [47]:
a4.ndim

3

In [50]:
np.random.rand(5,4)

array([[0.83872197, 0.19703268, 0.86494661, 0.17361028],
       [0.09492079, 0.29481844, 0.26340537, 0.19996674],
       [0.48383663, 0.32948882, 0.79670072, 0.56090936],
       [0.84665436, 0.46442377, 0.84342597, 0.07273429],
       [0.22191978, 0.66172678, 0.64648677, 0.33468303]])

In [52]:
# mean = 0, standard deviation = 1
#sum of 1st column is 0, 
a5 = np.random.randn(4,4)

In [57]:
# You have to reshare of same number of elements, we had 4*4 = 16 it has to be 16 , 2rows , 8 columns
a5.reshape(2,8)

array([[-1.89156365,  1.18949161, -0.92187639, -1.71248689,  0.11497492,
        -1.37550915, -1.13056196, -0.52948549],
       [ 0.87101969, -1.6312213 ,  1.04553243, -0.30975693,  0.7361598 ,
        -0.26552434, -0.81519855,  0.50908705]])

In [58]:
a5.reshape(8,2)

array([[-1.89156365,  1.18949161],
       [-0.92187639, -1.71248689],
       [ 0.11497492, -1.37550915],
       [-1.13056196, -0.52948549],
       [ 0.87101969, -1.6312213 ],
       [ 1.04553243, -0.30975693],
       [ 0.7361598 , -0.26552434],
       [-0.81519855,  0.50908705]])

In [59]:
#in case of -1, it will calculate the number of elecments, in this case its 16, 2 * -1(8)
a5.reshape(2,-1)

array([[-1.89156365,  1.18949161, -0.92187639, -1.71248689,  0.11497492,
        -1.37550915, -1.13056196, -0.52948549],
       [ 0.87101969, -1.6312213 ,  1.04553243, -0.30975693,  0.7361598 ,
        -0.26552434, -0.81519855,  0.50908705]])

In [61]:
# Same elements, you can reshare to any dimentional, 2 z, 2 rows , 4 columns)}
a5.reshape(2,2,4)

array([[[-1.89156365,  1.18949161, -0.92187639, -1.71248689],
        [ 0.11497492, -1.37550915, -1.13056196, -0.52948549]],

       [[ 0.87101969, -1.6312213 ,  1.04553243, -0.30975693],
        [ 0.7361598 , -0.26552434, -0.81519855,  0.50908705]]])

In [62]:
a5.reshape(1,1,1,2,2,4)

array([[[[[[-1.89156365,  1.18949161, -0.92187639, -1.71248689],
           [ 0.11497492, -1.37550915, -1.13056196, -0.52948549]],

          [[ 0.87101969, -1.6312213 ,  1.04553243, -0.30975693],
           [ 0.7361598 , -0.26552434, -0.81519855,  0.50908705]]]]]])

In [63]:
a1

array(['4', '5', '6', '7', 'sudh', '34.566', 'True'], dtype='<U32')

In [64]:
a1[0]

'4'

In [66]:
#start from 2 and exclude last element
a1[2:6]

array(['6', '7', 'sudh', '34.566'], dtype='<U32')

In [67]:
#start from 2 and exclude last element and jump of 2

a1[2:6:2]

array(['6', 'sudh'], dtype='<U32')

In [68]:
#reverse the list
a1[::-1]

array(['True', '34.566', 'sudh', '7', '6', '5', '4'], dtype='<U32')

In [69]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
a2[0]

array([1, 2, 3])

In [72]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [73]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

In [74]:
a2[[0,1],1:]

array([[2, 3],
       [5, 6]])

In [75]:
a6= np.random.randint(2,90,(6,5))

In [76]:
a6

array([[52, 73, 22, 29, 88],
       [86, 17, 22,  9, 49],
       [75, 53, 24, 38, 85],
       [89, 10, 72, 84, 85],
       [43, 85, 74, 56, 34],
       [79, 48, 72, 13, 87]])

In [78]:
# operations like pandas
a6[a6>40]

array([52, 73, 88, 86, 49, 75, 53, 85, 89, 72, 84, 85, 43, 85, 74, 56, 79,
       48, 72, 87])

In [79]:
a6[0,1] 

73

In [80]:
a6[0,1] =100

In [81]:
a6

array([[ 52, 100,  22,  29,  88],
       [ 86,  17,  22,   9,  49],
       [ 75,  53,  24,  38,  85],
       [ 89,  10,  72,  84,  85],
       [ 43,  85,  74,  56,  34],
       [ 79,  48,  72,  13,  87]])

In [85]:
a7 = np.random.randint(0,3,(3,3))

In [86]:
a8 = np.random.randint(0,3,(3,3))

In [87]:
a7

array([[2, 0, 0],
       [2, 2, 0],
       [2, 0, 2]])

In [88]:
a8

array([[1, 2, 1],
       [0, 2, 0],
       [2, 2, 2]])

In [89]:
a7*a8

array([[2, 0, 0],
       [0, 4, 0],
       [4, 0, 4]])

In [91]:
#Metrics multiplication
a7@a8

array([[2, 4, 2],
       [2, 8, 2],
       [6, 8, 6]])

In [92]:
a7+100

array([[102, 100, 100],
       [102, 102, 100],
       [102, 100, 102]])

In [93]:
a7*2

array([[4, 0, 0],
       [4, 4, 0],
       [4, 0, 4]])

In [96]:
a7/0

/var/folders/d4/fq89d3wx7fzbh91frkkvyw600000gn/T/ipykernel_7083/2765990889.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a7/0
/var/folders/d4/fq89d3wx7fzbh91frkkvyw600000gn/T/ipykernel_7083/2765990889.py:1: RuntimeWarning: invalid value encountered in true_divide
  a7/0


array([[inf, nan, nan],
       [inf, inf, nan],
       [inf, nan, inf]])

In [97]:
a7**3

array([[8, 0, 0],
       [8, 8, 0],
       [8, 0, 8]])

In [100]:
a9=np.zeros((4,4))

In [101]:
a9

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [102]:
a10 = np.ones((4,5))

In [103]:
a10

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [105]:
a9 +10

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [106]:
a9

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [107]:
a10

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [112]:
#addition row wise addition
a10 + np.array([1,2,3,4,5])

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [111]:
#you can not different column size
a10 + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [115]:
#column size broadcasting operation, you can use transprot 
np.array([[1,2,3,4]]).T + a10

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [116]:
a7

array([[2, 0, 0],
       [2, 2, 0],
       [2, 0, 2]])

In [117]:
a7.T

array([[2, 2, 2],
       [0, 2, 0],
       [0, 0, 2]])

In [118]:
a6

array([[ 52, 100,  22,  29,  88],
       [ 86,  17,  22,   9,  49],
       [ 75,  53,  24,  38,  85],
       [ 89,  10,  72,  84,  85],
       [ 43,  85,  74,  56,  34],
       [ 79,  48,  72,  13,  87]])

In [119]:
np.sqrt(a6)

array([[ 7.21110255, 10.        ,  4.69041576,  5.38516481,  9.38083152],
       [ 9.2736185 ,  4.12310563,  4.69041576,  3.        ,  7.        ],
       [ 8.66025404,  7.28010989,  4.89897949,  6.164414  ,  9.21954446],
       [ 9.43398113,  3.16227766,  8.48528137,  9.16515139,  9.21954446],
       [ 6.55743852,  9.21954446,  8.60232527,  7.48331477,  5.83095189],
       [ 8.88819442,  6.92820323,  8.48528137,  3.60555128,  9.32737905]])

In [120]:
np.exp(a6)

array([[3.83100800e+22, 2.68811714e+43, 3.58491285e+09, 3.93133430e+12,
        1.65163625e+38],
       [2.23524660e+37, 2.41549528e+07, 3.58491285e+09, 8.10308393e+03,
        1.90734657e+21],
       [3.73324200e+32, 1.04137594e+23, 2.64891221e+10, 3.18559318e+16,
        8.22301271e+36],
       [4.48961282e+38, 2.20264658e+04, 1.85867175e+31, 3.02507732e+36,
        8.22301271e+36],
       [4.72783947e+18, 8.22301271e+36, 1.37338298e+32, 2.09165950e+24,
        5.83461743e+14],
       [2.03828107e+34, 7.01673591e+20, 1.85867175e+31, 4.42413392e+05,
        6.07603023e+37]])

In [121]:
np.log10(a6)

array([[1.71600334, 2.        , 1.34242268, 1.462398  , 1.94448267],
       [1.93449845, 1.23044892, 1.34242268, 0.95424251, 1.69019608],
       [1.87506126, 1.72427587, 1.38021124, 1.5797836 , 1.92941893],
       [1.94939001, 1.        , 1.8573325 , 1.92427929, 1.92941893],
       [1.63346846, 1.92941893, 1.86923172, 1.74818803, 1.53147892],
       [1.89762709, 1.68124124, 1.8573325 , 1.11394335, 1.93951925]])

In [124]:
#starts with 0, ingnors 10
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [125]:
#starts with 0, ingnors 10 , you can add too jump
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [130]:
# in normal range you can not jump decimal number
list(range(0,10,2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [129]:
# numpy you can provide jump number so decimal
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [132]:
np.linspace(2,3, num=50)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [133]:
np.linspace(2,3, num=50, retstep= True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [135]:
np.logspace(2,4,num=4, base=10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [142]:
########## Data visualization #####################
import cufflinks as cf
import numpy as np
import pandas as pd
import seaborn as sns

In [140]:
cf.go_offline()

In [144]:
df =pd.DataFrame(np.random.randn(100,3), columns=['A','B','C'])

In [145]:
df

A         B         C
0   0.128146 -0.235755 -1.287898
1  -0.094076 -1.341630  0.524306
2  -0.125927  0.528350  0.333865
3   0.539225  0.412971 -2.768361
4   0.946709  1.447163  0.074976
..       ...       ...       ...
95 -0.641265  0.252628  0.379024
96 -0.838389 -0.716576 -1.477114
97  1.099460 -1.899773 -0.051023
98  0.752457  1.517048  0.523530
99 -0.617685  0.139146 -0.745990

[100 rows x 3 columns]

In [148]:
df.iplot()

In [151]:
#comparision A and B columns
df.iplot(x='A', y ='B',mode='markers')

In [154]:
#default dataset available in sybol
df2 =sns.load_dataset('titanic')

In [155]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [156]:
df2.iplot(x ='age', y ='fare' , mode= 'markers')

In [157]:
df2.iplot(x ='age', y ='pclass' , mode= 'markers')

In [159]:
df2.iplot(y ='fare', x ='pclass' , mode= 'markers')

In [160]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [161]:
df2.iplot( kind='bar' , x= 'sex' , y ='survived')